package com.mybatis.entityDao;

public class Department {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.id
     *
     * @mbg.generated Wed Jul 24 17:40:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_dept.detp_name
     *
     * @mbg.generated Wed Jul 24 17:40:02 CST 2019
     */
    private String detpName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.id
     *
     * @return the value of tb_dept.id
     *
     * @mbg.generated Wed Jul 24 17:40:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.id
     *
     * @param id the value for tb_dept.id
     *
     * @mbg.generated Wed Jul 24 17:40:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_dept.detp_name
     *
     * @return the value of tb_dept.detp_name
     *
     * @mbg.generated Wed Jul 24 17:40:02 CST 2019
     */
    public String getDetpName() {
        return detpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_dept.detp_name
     *
     * @param detpName the value for tb_dept.detp_name
     *
     * @mbg.generated Wed Jul 24 17:40:02 CST 2019
     */
    public void setDetpName(String detpName) {
        this.detpName = detpName == null ? null : detpName.trim();
    }
}